### ISSUE TITLE
Login via Google

### ISSUE THREAD

**Issue by wmsmigiel** [EugeneTheDev/TaigaMobile#11]
Is it possible to login into the client if my account is authorized via google credentials? If not, is this functionality planned at any time in the future?

**Comment by EugeneTheDev** [comment]
Unfortunately, this cannot be done. In order to set up authentication via Google you need to configure it for particular server you want to interact with (of course this is not possible because that app is made for any Taiga instance possible). Moreover, due to Google limitations you cannot auth your app via Google Auth for more than one server. Because each client (in our particular case android app) can be connected **only with one server**.  So if your account is authorized via Google, I can only recommend you to visit your profile settings page in Taiga and set up login / password.

**Comment by philtweir** [comment]
Just for anyone like me who has github/gitlab login and is being daft - the Profile->Settings page would not let me add a password, as the current password field was empty (error) or wrong (also error). Logging out and resetting my password let me create one.
