### ISSUE TITLE
Wiki implementation 

### ISSUE THREAD

**Issue by onkoe** [EugeneTheDev/TaigaMobile#41]
We use Taiga as a way to plan our project. We also document planned changes and long-form conversations in wiki pages. Are there any plans to implement the Taiga wiki in Taiga Mobile? Thanks for the great app, by the way - very helpful for us!

**Comment by EugeneTheDev** [comment]
We have this in our backlog with low priority, since it seems there are not many people using the wiki option in Taiga. Unfortunately, we are a bit short on resources (both human and time), so we try to implement the most used features first. Anyway, thanks for reaching out, we'll move it up in backlog and implement this feature as soon as we sort out other more urgent tasks.
