### ISSUE TITLE
Feature Request: Save filter selection on scrum backlog screen

### ISSUE THREAD

**Issue by briaguya-ai** [EugeneTheDev/TaigaMobile#46]
### reproduction steps
1. select a filter on the scrum backlog screen
1. switch over to board/epics/issues etc.
1. switch back to the scrum backlog screen

### expected behavior
the selected filters from before are still selected

### observed behavior
no filters are selected

**Comment by EugeneTheDev** [comment]
For now "primary screens" - those which you navigate using bottom and "More" menu - don't preserve their state when you're navigating between them. So if you navigate, for example, from "Scrum" screen to task screen, edit this task and then return - the state will be preserved (only specific task item would be updated). But, as you've noticed, that's not the case when you're navigating, for example, from "Scrum" screen to "Issues" screen. This means that we would need to support state preservation between those "primary screens" in general. But then the information can become outdated on these screens. It's possible to implement manual refreshing (like swipe-to-refresh), but I don't think that's a good idea since users would forget about this and inevitably face with some strange errors due to desynchronisation. Silent refreshing is much more tricky and at this moment I don't have any clear ideas how to implement this to both refresh all the information and preserve the state. If you have any suggestions regarding implementation - either from the user side (UI/UX part) or from the technical side (how this might work under the hood) - let's discuss it

**Comment by briaguya-ai** [comment]
## introduction/reply

>  then the information on these screens can become outdated

this is an edge case scenario, like if a user has a filter selected and the project gets updated and that filter is deleted. this should be considered as a requirement for implementation, but it by no means prevents implementing the functionality.

the overall idea idea would be to keep the selected filters saved in persistent data somewhere, and when refreshing a project re-applying the saved filters, so

## where would it make sense to store this data?
i think settings 
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/state/Settings.kt#L8
is the best option, then it can be pulled it in like
https://github.com/EugeneTheDev/TaigaMobile/blob/cd6f44493065d8a8df03f6f4ef32790d825ce7e6/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/main/MainViewModel.kt#L12
and read from in all the places activeFilters gets reset
### where are all the places activeFilters gets reset?
https://github.com/EugeneTheDev/TaigaMobile/blob/2ea06035c92a0bc72723cf2e01a805be208606af/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/scrum/ScrumScreen.kt#L79
https://github.com/EugeneTheDev/TaigaMobile/blob/2ea06035c92a0bc72723cf2e01a805be208606af/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/scrum/ScrumScreen.kt#L55
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/scrum/ScrumViewModel.kt#L50
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/scrum/ScrumViewModel.kt#L86
i didn't look much outside of `ScrumViewModel`, but it seems like this is where all the resetting happens. 
#### how can we ensure the data is available to us at those times?
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/scrum/ScrumViewModel.kt#L29
is already there, if `Settings` gets pulled in the same way it seems like it should work
### what happens when activeFilters are set?
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/scrum/ScrumViewModel.kt#L60-L62
#### where is that data living currently?
looks like right on the model and that's it?
#### so how do we save it to settings instead?
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/ui/screens/settings/SettingsViewModel.kt#L37-L39
https://github.com/EugeneTheDev/TaigaMobile/blob/0f5dbaf7ef3cbb3ce9bda1e3cd7688692127b536/app/src/main/kotlin/io/eugenethedev/taigamobile/state/Settings.kt#L13-L16
following that pattern seems like a good plan

so so far we have
- [x] where to store the data
- [x] a pattern to follow for storing data there
- [ ] a way to ensure active filters are stored *per-project*

### how do we store the activeFilters per project?
depeding on how unique the ids are on the filter interface, it may not matter what project is loaded, and it could just be a matter of saving each active filter id to settings
https://github.com/EugeneTheDev/TaigaMobile/blob/ab6f371ab7ea189d671574b8306f2c45ad76b8ea/app/src/main/kotlin/io/eugenethedev/taigamobile/domain/entities/Filters.kt#L36-L37
if that's not the case, then probably using a combo of filter id and project id

### conclusion

this definitely isn't everything, but it seems like a decent place to start for trying to make this work.

**Comment by briaguya-ai** [comment]
made a wip pr, next thing to figure out is how to use the saved ids in settings to set activeFilters when filters are loaded
